name: Trigger auto deployment for dotnetcontainerapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/dotnetcontainerapp-AutoDeployTrigger-d1d56e4c-afb2-4c6e-bedb-7c5b2dbb4c10.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.DOTNETCONTAINERAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.DOTNETCONTAINERAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.DOTNETCONTAINERAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.DOTNETCONTAINERAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.DOTNETCONTAINERAPP_REGISTRY_PASSWORD }}
          containerAppName: dotnetcontainerapp
          resourceGroup: PrasadRG
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


