name: MyWebApplication

on:
  push:
    branches: [ "main"]

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./MyWebApplication

    steps:
      - uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: Restore Packages
        run: nuget restore MyWebApplication.sln

      - name: Build Solution
        run: |
          msbuild.exe MyWebApplication.sln /nologo /nr:false /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" /p:PublishUrl="../_build"
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: MyWebApplication
          package: "./_build"
