name: MyWebApplication

on:
  push:
    branches: [ "main"]

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./MyWebApplication

    steps:
      - uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: Restore Packages
        run: nuget restore MyWebApplication.sln

      - name: SonarQube Begin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          D:\SonarCloud\SonarScanner\SonarScanner.MSBuild.exe begin /k:"MyWebApplication" /n:"MyWebApplication" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}"

      - name: Build Solution
        run: |
          msbuild.exe MyWebApplication.sln /nologo /nr:false /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" /p:PublishUrl="../_build"

      - name: ReBuild Solution
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          shell: powershell
        run: |
           msbuild.exe build MyWebApplication.sln
          
      - name: SonarQube End
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          D:\SonarCloud\SonarScanner\SonarScanner.MSBuild.exe end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
     
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: MyWebApplication
          path: "./_build"
